name: Run nix build on repo.
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        continue-on-error: true
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}
          gc-max-store-size-linux: 1G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-${{ runner.arch }}
          purge-created: 0
          purge-last-accessed: 0
          purge-primary-key: never
      - name: nix build
        id: build
        run: |
          nix build
          # Execute the script to generate images
          sudo ./result --build-memory 4096
          # Package the generated images
          tar cvhzf images.tar.gz *.raw
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: |
            # Release: Pre-built NixOS Image for Odroid M2

            This release provides a **pre-built NixOS image** tailored for the Odroid M2 board, enabling you to get started without having to build from source.

            ---

            ## 📦 Included Files

            The downloadable archive `images.tar.gz` contains:

            - **`main.raw`** — The bootable NixOS disk image for Odroid M2 (built with disko).

            ## 🚀 Usage

            1. Extract the archive: `tar -xzf images.tar.gz`
            2. Flash to SD card/eMMC: `dd if=main.raw of=/dev/sdX bs=4M status=progress`
            3. Boot your Odroid M2!

            Default login: `root` / `odroid`
          files: |
            images.tar.gz
